import React,{useEffect,useRef,useState} from 'react';
import {ListIcon,XIcon,TimerIcon,ShieldCheckIcon,CookingPotIcon,GiftIcon,PhoneIcon,EnvelopeSimpleIcon,ClockIcon,MagnifyingGlassIcon,UsersIcon,CakeIcon,BuildingsIcon,HeartIcon,HandHeartIcon,CaretRightIcon} from '@phosphor-icons/react';
import {menu,categories,imageUrl,email,phone} from './menu';

import {DietaryConsiderations,DeliveryNotice,ContactToOrder} from './customer-care';
const links=[['home','Home'],['about','About'],['menu','Menu'],['catering','Catering'],['order','Order'],['contact','Contact Us']];
function Logo(){return <img className="brand-image" src="/assets/logo.png" alt="YamZah Kitchen"/>}
function Benefits(){return <div className="benefits">{[[TimerIcon,'Freshly prepared daily'],[CookingPotIcon,'Authentic Nigerian flavours'],[ShieldCheckIcon,'Hygienic & safe'],[GiftIcon,'Catering for all occasions']].map(([Icon,b])=><div key={b}><Icon size={30}/><span>{b}</span></div>)}</div>}
function Dialog({children,onClose,title,wide=false}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[]);return <dialog ref={ref} className={wide?'wide-dialog':''} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><button className="icon-button close-dialog" aria-label={`Close ${title}`} onClick={onClose}><XIcon size={22}/></button>{children}</dialog>}
function PageHeader({eyebrow,title,children}){return <section className="page-header"><div className="container"><p className="eyebrow">{eyebrow}</p>{title&&<h1>{title}</h1>}{children&&<p>{children}</p>}</div></section>}
function Card({item,compact=false,onOpen}){return <article className="food-card"><button className="food-open" onClick={()=>onOpen(item)} aria-label={`View ${item.name}`}>{item.image&&<img src={imageUrl(item)} alt={item.name} loading="lazy"/>}<span className="food-name">{item.name}</span></button><div className="food-content">{!compact&&<p>{item.description}</p>}{item.portion&&<small>{item.portion}</small>}<a className="button card-add" href="#order">Contact to order</a></div></article>}
export function App(){
const [page,setPage]=useState(location.hash.slice(1)||'home'),[mobileNav,setMobileNav]=useState(false),[product,setProduct]=useState(null),[filter,setFilter]=useState('All'),[search,setSearch]=useState('');
useEffect(()=>{const fn=()=>{setPage(location.hash.slice(1)||'home');setMobileNav(false);window.scrollTo(0,0)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
useEffect(()=>{try{localStorage.removeItem('yamzah-basket')}catch{}},[]);
useEffect(()=>{document.title=`${links.find(l=>l[0]===page)?.[1]||'Home'} | YamZah Kitchen`},[page]);
function openProduct(item){setProduct(item)}
const cards=items=>items.map(item=><Card key={item.id} item={item} onOpen={openProduct}/>);
return <><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content').focus()}}>Skip to content</a><div className="top-strip">Ready-made Nigerian meals, cooked fresh daily.<a href={`tel:+44${phone.slice(1)}`}><PhoneIcon size={14}/>{phone}</a></div><header className="site-header"><div className="container nav-wrap"><a href="#home" className="brand" aria-label="YamZah Kitchen home"><Logo/></a><nav className={mobileNav?'navigation open':'navigation'} aria-label="Main navigation">{links.map(([id,label])=><a key={id} href={`#${id}`} className={page===id?'active':''} aria-current={page===id?'page':undefined}>{label}</a>)}</nav><div className="nav-actions"><a className="icon-button" href="#menu" aria-label="Search menu" onClick={()=>setTimeout(()=>document.getElementById('menu-search')?.focus(),100)}><MagnifyingGlassIcon size={23}/></a><a href="#order" className="icon-button" aria-label="Contact to order"><PhoneIcon size={25}/></a><button className="icon-button menu-toggle" aria-label={mobileNav?'Close navigation':'Open navigation'} aria-expanded={mobileNav} onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<XIcon size={25}/>:<ListIcon size={25}/>}</button><a className="halal-header" href="#about" aria-label="Halal kitchen — dietary information"><img src="/assets/halal.png" alt="Halal"/></a></div></div></header>
<main id="main-content" tabIndex={-1}>
{(!links.some(l=>l[0]===page)||page==='home')&&<><section className="hero"><img className="hero-image" src="/assets/hero.png" alt="Smoky Nigerian jollof rice with grilled chicken"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">AUTHENTIC NIGERIAN MEALS</p><h1>Good Food<br/>Brings People<br/>Together</h1><p>Ready-made Nigerian meals, cooked fresh daily. Authentic flavours, convenient portions, for your everyday enjoyment and special occasions.</p><div className="button-row"><a className="button" href="#menu">View Menu</a><a className="button hero-secondary" href="#catering">Bulk Catering</a></div></div><p className="hero-note">Real Nigerian Meals.<br/>Real Goodness.</p></div></section><div className="container home-content"><Benefits/><section className="featured"><div className="section-heading"><div><p className="eyebrow">A TASTE OF HOME</p><h2>Featured Dishes</h2></div><a className="text-link" href="#menu">View full menu <CaretRightIcon/></a></div><div className="food-grid featured-grid">{['jollof','egusi','pepper','ayamase'].map(id=><Card key={id} item={menu.find(m=>m.id===id)} compact onOpen={openProduct}/>)}</div></section><section className="promo-grid"><article className="promo meals-promo"><div><p className="eyebrow">FRESH. CONVENIENT. DELICIOUS.</p><h2>Ready-made<br/>Meals</h2><p>Authentic Nigerian meals in convenient portions.</p><a className="button" href="#menu">View Menu</a></div><img src="/assets/packaging.png" alt="YamZah Kitchen ready meal packaging" loading="lazy"/></article><article className="promo catering-promo"><div><p className="eyebrow">LET US FEED YOUR GUESTS</p><h2>Bulk Catering<br/>For Every Occasion</h2><p>Delicious Nigerian meals for weddings, birthdays and celebrations, tailored to your needs.</p><a className="button" href="#catering">Request a Quote</a></div><img src="/assets/catering.png" alt="Nigerian food buffet prepared for an event" loading="lazy"/></article></section></div></>}
{page==='menu'&&<><PageHeader eyebrow="FRESH FROM OUR KITCHEN" title="Our Menu">A wide range of ready-made Nigerian meals, cooked with authentic flavours.</PageHeader><section className="container menu-section"><DeliveryNotice/><div className="menu-toolbar"><div className="filters" aria-label="Menu categories">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} aria-pressed={filter===c} className={filter===c?'selected':''}>{c}</button>)}</div><label className="search-field"><MagnifyingGlassIcon size={20}/><input id="menu-search" aria-label="Search dishes" placeholder="Find your favourite…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p className="menu-note">To place an order, please contact YamZah Kitchen by phone or email.</p>{categories.slice(1).map(cat=>{const items=menu.filter(m=>(filter==='All'||filter===cat)&&m.category===cat&&(m.name+' '+m.description).toLowerCase().includes(search.toLowerCase()));return items.length?<section className="menu-group" key={cat}><h2>{cat==='Starter'?'Starters':cat==='Main'?'Main Meals':cat}</h2><div className="food-grid">{cards(items)}</div></section>:null})}{!menu.some(m=>(filter==='All'||m.category===filter)&&(m.name+' '+m.description).toLowerCase().includes(search.toLowerCase()))&&<div className="empty-state"><MagnifyingGlassIcon size={42}/><h2>No dishes found</h2><p>Try another dish name or browse all categories.</p><button className="button" onClick={()=>{setSearch('');setFilter('All')}}>Show all dishes</button></div>}<p className="allergen-note">Food allergies or dietary requirements? Please speak with us before ordering. Our kitchen handles common allergens, including nuts, eggs, fish and wheat.</p></section></>}
{page==='catering'&&<><PageHeader eyebrow="GOOD FOOD. UNFORGETTABLE OCCASIONS." title="Bulk Catering">From intimate gatherings to grand celebrations, let us bring the taste of home.</PageHeader><div className="container catering-layout"><aside><img className="catering-photo" src="/assets/catering.png" alt="Nigerian catering buffet"/><h2>For Every Occasion</h2><p>Beautiful food brings everyone together. Choose the dishes you love and tell us about your event. We’ll help you plan the rest.</p><div className="occasion-list">{[[HeartIcon,'Weddings'],[CakeIcon,'Birthdays'],[HandHeartIcon,'Religious gatherings'],[BuildingsIcon,'Corporate events'],[UsersIcon,'Memorials']].map(([Icon,label])=><div key={label}><Icon size={25}/>{label}</div>)}</div><div className="collection-note"><CookingPotIcon size={30}/><div><strong>Collection recommended</strong><p>Delivery is available at an additional cost depending on your location.</p></div></div></aside><ContactToOrder catering/></div></>}
{page==='order'&&<><PageHeader eyebrow="LET’S PLAN YOUR NEXT MEAL" title="Contact to Order">Please contact YamZah Kitchen to make your order.</PageHeader><div className="container order-section"><DeliveryNotice/><ContactToOrder/><div className="button-row"><a className="button secondary" href="#menu">Explore the Menu</a><a className="button secondary" href="#catering">Catering for Your Event</a></div></div></>}
{page==='about'&&<><PageHeader eyebrow="OUR KITCHEN. YOUR HOME.">Good food brings people together.</PageHeader><section className="container about-layout"><img src="/assets/hero.png" alt="Freshly prepared Nigerian rice and chicken"/><div><p className="eyebrow">NIGERIAN MEALS. REAL GOODNESS.</p><h2>A taste of home,<br/>made with love.</h2><p>At YamZah Kitchen, we are passionate about bringing the rich flavours of Nigeria to your table. Our ready-made meals are cooked fresh daily using authentic ingredients, offering you the taste of home, anytime, anywhere.</p><p>From a comforting bowl of soup to a celebration shared with family and friends, explore everyday favourites and catering for your special occasions.</p><div className="button-row"><a className="button" href="#menu">Explore Our Menu</a><a className="button secondary" href="#catering">Plan Your Event</a></div></div></section><div className="container"><Benefits/></div><DietaryConsiderations/></>}
{page==='contact'&&<><PageHeader eyebrow="WE’D LOVE TO HEAR FROM YOU" title="Contact Us">A meal for today or a celebration to plan, Talk to our kitchen.</PageHeader><div className="container contact-layout"><section className="contact-card"><h2>Our Information</h2><div><ClockIcon/><section><h3>Opening Hours</h3><p>Monday – Friday: 12pm – 7pm<br/>Saturday – Sunday: 9am – 8pm</p></section></div><div><EnvelopeSimpleIcon/><section><h3>Email</h3><a href={`mailto:${email}`}>{email}</a></section></div><div><PhoneIcon/><section><h3>Phone</h3><a href={`tel:+44${phone.slice(1)}`}>{phone}</a></section></div><p className="fine-print">Please contact us to confirm collection arrangements, availability and delivery costs.</p></section><section className="contact-invite"><img src="/assets/catering.png" alt="Fresh meals ready to serve"/><div><h2>Make it an occasion</h2><p>Tell us what you’re planning and choose your favourite dishes.</p><a href="#catering" className="button">Request a Catering Quote</a></div></section></div></>}
</main><footer><div className="container footer-top"><a className="brand footer-brand" href="#home"><Logo/></a><p>Ready-made Nigerian meals,<br/>cooked fresh daily.</p><div><a href={`mailto:${email}`}>{email}</a><a href={`tel:+44${phone.slice(1)}`}>{phone}</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} YamZah Kitchen</span><span>Good food. Brighter days.</span><a href="#contact">Contact our kitchen</a></div></footer>
{product&&<Dialog title={product.name} onClose={()=>setProduct(null)} wide><div className="product-detail">{product.image&&<img src={imageUrl(product)} alt={product.name}/>}<section><p className="eyebrow">{product.category}</p><h2>{product.name}</h2><p>{product.description}</p>{product.portion&&<p>{product.portion}</p>}<p>Contact our kitchen to arrange your meal and discuss portions, spice preferences and dietary requirements.</p><a className="button full" href="#order" onClick={()=>setProduct(null)}>Contact to order</a></section></div></Dialog>}</>;
}
